### ISSUE TITLE
Idea for including compilation steps in the README

### ISSUE THREAD

**Issue by ghost** [mfat/bootselector#2]
Hi, I have an advice to add running steps in the README. This would make the job of compiling the program easily. Please list all the required libraries to be installed I tried it on the latest version of Arch Linux- It showed up this error

![Screenshot From 2024-12-13 22-16-27](https://github.com/user-attachments/assets/12ef4500-b477-49ab-a265-603ab01a1633)

This is the error, I have grub and many of its dependencies like python-gobject, gtk3 and polkit. It still not works, hope you would give me a resolution for this error

**Comment by mfat** [comment]
How did you install this on Arch linux? Did you run the py file?

**Comment by mfat** [comment]
Also you can use this on arch linux. I'll update the readme. https://aur.archlinux.org/packages/update-grub

make sure to create a symlink too:
`sudo ln -s /usr/bin/update-grub /usr/sbin/update-grub`

**Comment by ghost** [comment]
Yes, I ran the python script. Thanks for including steps for running it on Arch Linux.
